version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=c92e1402-3dfb-4dd9-b22d-3bfe14e07ee7
      - ALGORITHM=HS256
      - EXPIRE_TIME_MIN=120
      - DATABASE_TYPE=postgresql
      - DATABASE_USER=postgres
      - DATABASE_HOST=localhost
      - DATABASE_NAME=fast_api_tutorial
      - DATABASE_PASSWORD=password
      - DATABASE_PORT=5432
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=fast_api_tutorial
#    ports:
#      - 5432:5432
#    volumes:
#      - postgres-db:/var/lib/postgresql/data
#volumes:
#  postgres-db: